spring.application.name=demo

# Temporary H2 database configuration for development
# Replace with PostgreSQL for Docker production deployment
spring.datasource.url=jdbc:h2:mem:fintech-stream;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 console (optional, for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
